<a href="https://colab.research.google.com/github/vinay722187-web/lernpyt/blob/main/day10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
#time comparison
import numpy as np
import time

start =time.time()
sum1 =0
for i in range  (100000):
  sum1+=i*2
end =time.time()
print('for list',sum1,end-start)

#for numpy  array (array work every element  elemt wise)

start1=time.time()
sum2=0
arr=np.arange(100000)*2
sum2=arr.sum()
end1=time.time()
print('for array',sum2,end1-start1)


for list 9999900000 0.016866445541381836
for array 9999900000 0.0009884834289550781


In [30]:
# zeros
# array 1d
import numpy as np
arr=np.zeros(5)
print(arr)

# array 2d
arr1=np.zeros((2,3)) #2 row and 3 coloumn
print(arr1)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
# ones
import numpy as np
#array 1d

arr=np.ones(5)
print(arr)

#arrqay 2d

arr=np.ones((3,4))
print(arr)

[1. 1. 1. 1. 1.]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [33]:
#full
import numpy as np
#array 1d
arr=np.full((5),7)
print(arr)

#arry 2d
arr=np.full((3,5),7)
print(arr)

[7 7 7 7 7]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [40]:
import numpy as np
# arr=np.zeros(5)+7
# print(arr)

arr1=np.zeros((3,4))+7
print(arr)

[7. 7. 7. 7. 7.]


In [42]:
import numpy as np
arr=np.zeros(5)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


arr =np.zeros((3,4))
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[0. 0. 0. 0. 0.]
(5,)
1
5
float64
[0. 0. 0. 0. 0.]
(5,)
1
5
float64


In [ ]:
import numpy as np
arr=np.ones(5)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


arr =np.ones((3,4))
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

In [46]:
import numpy as np
arr=np.full((5),7)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


arr =np.full((3,4),7)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[7 7 7 7 7]
(5,)
1
5
int64
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
(5,)
1
5
int64


In [59]:
#1d
import numpy as np
arr=np.arange(6)
print(arr)

#2d
arr1=arr.reshape(2,3)
print(arr1)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [72]:
#flatten
import numpy as np
#2d
arr=np.arange(6)

arr1=arr.reshape(2,3)
print(arr1)

#flatten

print(arr1.flatten())

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


In [71]:
#ravel
import numpy as np
arr=np.arange(6).reshape(2,3)

print(arr)

#ravel
print(arr.ravel())

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


In [78]:
#flatten
import numpy as np
#2d
arr=np.arange(6)

arr1=arr.reshape(2,3)             #ravel me original values me change nahi hota hai
print(arr1)

#flatten
arr_new=arr1.flatten()
arr_new[0]=100

print(arr1)


[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]


In [79]:
#ravel
import numpy as np
arr=np.arange(6).reshape(2,3)

print(arr)                      #ravel me original values me change hota hai

#ravel                          #ravel return original
arr_new=arr1.ravel()
arr_new[0]=100
print(arr1)

[[0 1 2]
 [3 4 5]]
[[100   1   2]
 [  3   4   5]]


In [85]:
#transpose
#converts row into coloumn
import numpy as np
arr=np.arange(6).reshape(2,3)
print(arr)
arr1=arr.T # arr=arr.transpose
print(arr1) # print(arr)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
