<a href="https://colab.research.google.com/github/vinay722187-web/lernpyt/blob/main/day_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# file handling
# read
# write
# append


In [ ]:
from google.colab import drive
# drive.mount('/content/drive')

# read data
data = open("/content/drive/MyDrive/file1.csv","r")
data.read()

'name,roll no\ndheeraj,123\nkunal,1234\nabhishek,12345\npraveen,12356\nanjali,1234567'

In [ ]:
from google.colab import drive
# drive.mount('/content/drive')

data = open("/content/drive/MyDrive/hello.txt","r")
data.read()

'we r indians also aryansv r grasnv r grasnv r grasnv r grasnv r grasnv r grasnv r grasn'

In [ ]:
#read
data2=open('/content/drive/MyDrive/hello.txt','w')
data2.write('we r indians')

data2 = open('/content/drive/MyDrive/hello.txt','r')
data2.read()

'we r indians'

In [ ]:
from os import read
# write and read
data2=open('/content/drive/MyDrive/hello.txt','w')
data2.write('we r indians also aryans ')

data2 = open('/content/drive/MyDrive/hello.txt','r')
data2.read()

'we r indians also aryans'

In [ ]:
# read and append
data2=open('/content/drive/MyDrive/hello.txt','r')
data2.read()

data2=open('/content/drive/MyDrive/hello.txt','a')
data2.write('v r grasn')

data2=open('/content/drive/MyDrive/hello.txt','r')
data2.read()

'we r indians also aryansv r grasnv r grasnv r grasnv r grasnv r grasnv r grasnv r grasn'

In [ ]:
data =open('hello.txt','r')
data.read()


'vinay'

In [ ]:
data =open('file1.csv','r')
data.read()
# read and write and append ghar se kr kr lana hai

'name,roll no\ndheeraj,123\nkunal,1234\nabhishek,12345\npraveen,12356\nanjali,1234567'

In [ ]:
# NEW TOPIC NUMPy
# !import numpy as np
# !pip install numpy
import numpy as np
#1d
l=[10,20,30]
l


[10, 20, 30]

In [ ]:
import numpy as np
#1d
l=[10,20,30]
l

#power of numpty
kkkrr=np.array(l)
kkkrr*2




array([20, 40, 60])

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(arr[-1])

[1 2 3 4]
4


In [ ]:
import numpy as np
l=[10,20,30,40]
print(l)
print(type(l))

arr=np.array(l)
print(arr)
print(type(arr))

[10, 20, 30, 40]
<class 'list'>
[10 20 30 40]
<class 'numpy.ndarray'>


In [ ]:
# chnage value
import numpy as np
l=[1,2,3,4]
l[0]=100
print(l)

#numpy

arr=np.array(l)
arr[0]=200
arr[-1]=10000
print(arr)

[100, 2, 3, 4]
[  200     2     3 10000]


In [33]:
# value add=2
import numpy as np
l=[10,2,3,4]
# print(l+2) eRROR\\\\\//////////|\\\\\\\\\||||||||\\

arr=np.array(l)
print(arr+2)
arr[0]+=2
print(arr)

[12  4  5  6]
[12  2  3  4]


In [ ]:
# arange in numpy
import numpy as np
arr=np.arange(5) #start, stop, jump
print(arr)

[0 1 2 3 4]


In [ ]:
for i in range (1,13,3):
  print(i)

1
4
7
10


In [ ]:
# home work for 2d and 3d

In [38]:
# simple 2d example

import numpy as np
#this code is list
l=[[1,2,3,],[4,5,6]]
print(l)
print(l[0][1])

#numpy 2d
#this code is numpy
arr=np.array(l)
print(arr)
print(arr[1][2])



[[1, 2, 3], [4, 5, 6]]
2
[[1 2 3]
 [4 5 6]]
6
